/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Schedule = IDL.Record({
  'day' : IDL.Text,
  'subject' : IDL.Text,
  'time' : IDL.Text,
  'teacher' : IDL.Text,
  'schoolClass' : IDL.Nat,
});
export const MCQQuestion = IDL.Record({
  'text' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppRole = IDL.Variant({
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
  'student' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'status' : IDL.Text,
  'studentId' : IDL.Text,
  'subject' : IDL.Text,
  'date' : IDL.Text,
  'schoolClass' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'role' : AppRole,
  'passwordHash' : IDL.Text,
});
export const Doubt = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'subject' : IDL.Text,
  'teacher' : IDL.Opt(IDL.Text),
  'answer' : IDL.Opt(IDL.Text),
  'student' : IDL.Text,
  'schoolClass' : IDL.Nat,
});
export const LiveClass = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'joinLink' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'teacher' : IDL.Text,
  'schoolClass' : IDL.Nat,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'blob' : ExternalBlob,
  'teacher' : IDL.Text,
  'schoolClass' : IDL.Nat,
});
export const TestAttempt = IDL.Record({
  'id' : IDL.Nat,
  'answers' : IDL.Vec(IDL.Nat),
  'score' : IDL.Nat,
  'student' : IDL.Text,
  'testId' : IDL.Nat,
});
export const Test = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'teacher' : IDL.Text,
  'questions' : IDL.Vec(MCQQuestion),
  'schoolClass' : IDL.Nat,
});
export const VideoLecture = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'teacher' : IDL.Text,
  'schoolClass' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLiveClass' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addNote' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, ExternalBlob], [], []),
  'addSchedule' : IDL.Func([Schedule], [], []),
  'addTest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(MCQQuestion)],
      [],
      [],
    ),
  'addVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'answerDoubt' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUser' : IDL.Func([IDL.Text, IDL.Text, AppRole], [], []),
  'deleteLiveClass' : IDL.Func([IDL.Nat], [], []),
  'deleteSchedule' : IDL.Func([IDL.Nat], [], []),
  'deleteUser' : IDL.Func([IDL.Text], [], []),
  'getAttendanceByClass' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
  'getLiveClasses' : IDL.Func([], [IDL.Vec(LiveClass)], ['query']),
  'getLiveClassesByClass' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LiveClass)],
      ['query'],
    ),
  'getMonthlyAttendanceByClass' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getNotesByClass' : IDL.Func([IDL.Nat], [IDL.Vec(Note)], ['query']),
  'getSchedules' : IDL.Func([], [IDL.Vec(Schedule)], ['query']),
  'getStudentAttempts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TestAttempt)],
      ['query'],
    ),
  'getTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'getTestsByClass' : IDL.Func([IDL.Nat], [IDL.Vec(Test)], ['query']),
  'getUnansweredDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideos' : IDL.Func([], [IDL.Vec(VideoLecture)], ['query']),
  'getVideosByClass' : IDL.Func([IDL.Nat], [IDL.Vec(VideoLecture)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, AppRole))],
      ['query'],
    ),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'markAttendance' : IDL.Func([IDL.Vec(AttendanceRecord)], [], []),
  'postDoubt' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAttempt' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat], [], []),
  'updateSchedule' : IDL.Func([IDL.Nat, Schedule], [], []),
  'updateUser' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(AppRole)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Schedule = IDL.Record({
    'day' : IDL.Text,
    'subject' : IDL.Text,
    'time' : IDL.Text,
    'teacher' : IDL.Text,
    'schoolClass' : IDL.Nat,
  });
  const MCQQuestion = IDL.Record({
    'text' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppRole = IDL.Variant({
    'admin' : IDL.Null,
    'teacher' : IDL.Null,
    'student' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'status' : IDL.Text,
    'studentId' : IDL.Text,
    'subject' : IDL.Text,
    'date' : IDL.Text,
    'schoolClass' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'role' : AppRole,
    'passwordHash' : IDL.Text,
  });
  const Doubt = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'subject' : IDL.Text,
    'teacher' : IDL.Opt(IDL.Text),
    'answer' : IDL.Opt(IDL.Text),
    'student' : IDL.Text,
    'schoolClass' : IDL.Nat,
  });
  const LiveClass = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'joinLink' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'teacher' : IDL.Text,
    'schoolClass' : IDL.Nat,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'blob' : ExternalBlob,
    'teacher' : IDL.Text,
    'schoolClass' : IDL.Nat,
  });
  const TestAttempt = IDL.Record({
    'id' : IDL.Nat,
    'answers' : IDL.Vec(IDL.Nat),
    'score' : IDL.Nat,
    'student' : IDL.Text,
    'testId' : IDL.Nat,
  });
  const Test = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'teacher' : IDL.Text,
    'questions' : IDL.Vec(MCQQuestion),
    'schoolClass' : IDL.Nat,
  });
  const VideoLecture = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'teacher' : IDL.Text,
    'schoolClass' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLiveClass' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addNote' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, ExternalBlob], [], []),
    'addSchedule' : IDL.Func([Schedule], [], []),
    'addTest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(MCQQuestion)],
        [],
        [],
      ),
    'addVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'answerDoubt' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUser' : IDL.Func([IDL.Text, IDL.Text, AppRole], [], []),
    'deleteLiveClass' : IDL.Func([IDL.Nat], [], []),
    'deleteSchedule' : IDL.Func([IDL.Nat], [], []),
    'deleteUser' : IDL.Func([IDL.Text], [], []),
    'getAttendanceByClass' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
    'getLiveClasses' : IDL.Func([], [IDL.Vec(LiveClass)], ['query']),
    'getLiveClassesByClass' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LiveClass)],
        ['query'],
      ),
    'getMonthlyAttendanceByClass' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getNotesByClass' : IDL.Func([IDL.Nat], [IDL.Vec(Note)], ['query']),
    'getSchedules' : IDL.Func([], [IDL.Vec(Schedule)], ['query']),
    'getStudentAttempts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TestAttempt)],
        ['query'],
      ),
    'getTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'getTestsByClass' : IDL.Func([IDL.Nat], [IDL.Vec(Test)], ['query']),
    'getUnansweredDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideos' : IDL.Func([], [IDL.Vec(VideoLecture)], ['query']),
    'getVideosByClass' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(VideoLecture)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, AppRole))],
        ['query'],
      ),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'markAttendance' : IDL.Func([IDL.Vec(AttendanceRecord)], [], []),
    'postDoubt' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAttempt' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat], [], []),
    'updateSchedule' : IDL.Func([IDL.Nat, Schedule], [], []),
    'updateUser' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(AppRole)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };