/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'admin' : null } |
  { 'teacher' : null } |
  { 'student' : null };
export interface AttendanceRecord {
  'status' : string,
  'studentId' : string,
  'subject' : string,
  'date' : string,
  'schoolClass' : bigint,
}
export interface Doubt {
  'id' : bigint,
  'question' : string,
  'subject' : string,
  'teacher' : [] | [string],
  'answer' : [] | [string],
  'student' : string,
  'schoolClass' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface LiveClass {
  'id' : bigint,
  'title' : string,
  'subject' : string,
  'joinLink' : string,
  'date' : string,
  'time' : string,
  'teacher' : string,
  'schoolClass' : bigint,
}
export interface MCQQuestion {
  'text' : string,
  'correctAnswer' : bigint,
  'options' : Array<string>,
}
export interface Note {
  'id' : bigint,
  'title' : string,
  'subject' : string,
  'blob' : ExternalBlob,
  'teacher' : string,
  'schoolClass' : bigint,
}
export interface Schedule {
  'day' : string,
  'subject' : string,
  'time' : string,
  'teacher' : string,
  'schoolClass' : bigint,
}
export interface Test {
  'id' : bigint,
  'title' : string,
  'subject' : string,
  'teacher' : string,
  'questions' : Array<MCQQuestion>,
  'schoolClass' : bigint,
}
export interface TestAttempt {
  'id' : bigint,
  'answers' : Array<bigint>,
  'score' : bigint,
  'student' : string,
  'testId' : bigint,
}
export interface UserProfile {
  'username' : string,
  'role' : AppRole,
  'passwordHash' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoLecture {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'subject' : string,
  'teacher' : string,
  'schoolClass' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLiveClass' : ActorMethod<
    [string, string, bigint, string, string, string],
    undefined
  >,
  'addNote' : ActorMethod<[string, bigint, string, ExternalBlob], undefined>,
  'addSchedule' : ActorMethod<[Schedule], undefined>,
  'addTest' : ActorMethod<
    [string, bigint, string, Array<MCQQuestion>],
    undefined
  >,
  'addVideo' : ActorMethod<[string, string, bigint, string], undefined>,
  'answerDoubt' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUser' : ActorMethod<[string, string, AppRole], undefined>,
  'deleteLiveClass' : ActorMethod<[bigint], undefined>,
  'deleteSchedule' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[string], undefined>,
  'getAttendanceByClass' : ActorMethod<
    [bigint, string],
    Array<AttendanceRecord>
  >,
  'getAttendanceByStudent' : ActorMethod<
    [string, string, string],
    Array<AttendanceRecord>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoubts' : ActorMethod<[], Array<Doubt>>,
  'getLiveClasses' : ActorMethod<[], Array<LiveClass>>,
  'getLiveClassesByClass' : ActorMethod<[bigint], Array<LiveClass>>,
  'getMonthlyAttendanceByClass' : ActorMethod<
    [bigint, string, string],
    Array<AttendanceRecord>
  >,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getNotesByClass' : ActorMethod<[bigint], Array<Note>>,
  'getSchedules' : ActorMethod<[], Array<Schedule>>,
  'getStudentAttempts' : ActorMethod<[string], Array<TestAttempt>>,
  'getTests' : ActorMethod<[], Array<Test>>,
  'getTestsByClass' : ActorMethod<[bigint], Array<Test>>,
  'getUnansweredDoubts' : ActorMethod<[], Array<Doubt>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideos' : ActorMethod<[], Array<VideoLecture>>,
  'getVideosByClass' : ActorMethod<[bigint], Array<VideoLecture>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listUsers' : ActorMethod<[], Array<[string, AppRole]>>,
  'login' : ActorMethod<[string, string], boolean>,
  'markAttendance' : ActorMethod<[Array<AttendanceRecord>], undefined>,
  'postDoubt' : ActorMethod<[string, bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAttempt' : ActorMethod<[bigint, Array<bigint>, bigint], undefined>,
  'updateSchedule' : ActorMethod<[bigint, Schedule], undefined>,
  'updateUser' : ActorMethod<
    [string, [] | [string], [] | [AppRole]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];